POST http://localhost:3333/appointments HTTP/1.1
content-type: application/json

{
  "provider_id": "fc15f14e-3190-4fa0-b5de-5acc15fdfd0f",
  "date": "{{$localDatetime iso8601}}"
}

###
GET http://localhost:3333/appointments
